env = "dev"
http_addr = "0.0.0.0"
http_port = 8080
log_mode = "console"
log_file = "logs/app.log"
log_level = "debug"
access_log_file = "logs/access.log"
sql_log_file = "logs/sql.log"

[dbs]

[dbs.default]
uri = "root:root123456.@tcp(127.0.0.1:3306)/ginson?charset=utf8mb4&parseTime=True&loc=Local"
max_idle_conn = 5
max_open_conn = 50

[redis]
addr = "127.0.0.1:6379"
pass = ""
db = 1
min_idle = 10
pool_size = 64

# 业务配置在这里
[ext]
token_secret = "@fc695ewewqewqwqdaaaaa"
upload_image_path = "C:\\Users\\Administrator\\Desktop\\share\\images"

