env = "dev"
http_addr = "0.0.0.0"
http_port = 8080
log_mode = "console"
log_file = "logs/app.log"
log_level = "debug"

# 业务配置在这里
[ext]
token_secret = "@fc695ewewqewqwqdaaaaa"

# 微信小程序授权配置
wx_mini_app_id = ""
wx_mini_app_secret = ""

